version: '3.5'
services:
  php:
    build:
      context: ./docker/php
    volumes:
      - ./:/app
    depends_on:
      - redis
    tty: true

  redis:
    image: redis:6.2-alpine

  queue:
    command:
      - php
      - yii
      - queue/listen
      - --verbose
    build:
      context: ./docker/php
    volumes:
      - ./:/app
    depends_on:
      - php
    entrypoint: docker/php/entrypoint.sh
